//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace northwindCRUDByJQueryAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employees
    {
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
            PhotoPath = "~/AppFiles/images/default.png";
        }
    
        public int EmployeeID { get; set; }

        [DisplayName("姓氏")]
        [Required(ErrorMessage ="輸入姓氏")]
        public string LastName { get; set; }

        [DisplayName("名字")]
        [Required(ErrorMessage = "輸入名字")]
        public string FirstName { get; set; }

        [DisplayName("職稱")]
        [Required(ErrorMessage = "輸入職稱")]
        public string Title { get; set; }
        public string TitleOfCourtesy { get; set; }

        [DisplayName("生日")]
        [Required(ErrorMessage = "輸入生日")]
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }

        [DisplayName("居住地址")]
        [Required(ErrorMessage = "輸入居住地址")]
        public string Address { get; set; }

        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }

        [DisplayName("連絡電話")]
        [Required(ErrorMessage = "輸入連絡電話")]
        public string HomePhone { get; set; }

        [DisplayName("分機")]
        [Required(ErrorMessage = "輸入分機")]
        public string Extension { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ReportsTo { get; set; }

        [DisplayName("圖片路徑")]
        public string PhotoPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase fImageUpload { get; set; }
    
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
    }
}
